# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/GitHub_projects/Eclypse_Z7_Zmod_AWG/Eclypse_Z7_Zmod_AWG.srcs/sources_1/bd/design_1/ip/design_1_ZmodAWGController_0_0/design_1_ZmodAWGController_0_0.xci
# IP: The module: 'design_1_ZmodAWGController_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub_projects/Eclypse_Z7_Zmod_AWG/Eclypse_Z7_Zmod_AWG.gen/sources_1/bd/design_1/ip/design_1_ZmodAWGController_0_0/constr/ConstrZmodDAC1411_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ZmodAWGController_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub_projects/Eclypse_Z7_Zmod_AWG/Eclypse_Z7_Zmod_AWG.gen/sources_1/bd/design_1/ip/design_1_ZmodAWGController_0_0/constr/ConstrsZmodDAC1411.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ZmodAWGController_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/GitHub_projects/Eclypse_Z7_Zmod_AWG/Eclypse_Z7_Zmod_AWG.srcs/sources_1/bd/design_1/ip/design_1_ZmodAWGController_0_0/design_1_ZmodAWGController_0_0.xci
# IP: The module: 'design_1_ZmodAWGController_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/GitHub_projects/Eclypse_Z7_Zmod_AWG/Eclypse_Z7_Zmod_AWG.gen/sources_1/bd/design_1/ip/design_1_ZmodAWGController_0_0/constr/ConstrZmodDAC1411_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ZmodAWGController_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/GitHub_projects/Eclypse_Z7_Zmod_AWG/Eclypse_Z7_Zmod_AWG.gen/sources_1/bd/design_1/ip/design_1_ZmodAWGController_0_0/constr/ConstrsZmodDAC1411.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ZmodAWGController_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
